services:

  backend1:
    build: ./backend1
    working_dir: /app
    volumes:
      - ./backend1:/app
    command:
      - /bin/bash
      - -c
      - |
        composer install
        php artisan serve --host 0.0.0.0
    tty: true

  nginx:
    image: nginx:1.21.6-alpine
    ports:
      - 80:80
    volumes:
      - ./backend1:/app
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf